#!/bin/bash

function install_prerequisite() {
  sudo apt-get install --assume-yes jq unzip
}

function download_terraform() {
  # Get the latest version using the HashiCorp Releases API
  latest_version=$(curl -s https://api.releases.hashicorp.com/v1/releases/terraform | jq -r '.[].version' | sort -rV | head -n 1)

  # Construct download URL directly 
  terraform_url="https://releases.hashicorp.com/terraform/${latest_version}/terraform_${latest_version}_linux_amd64.zip"

  # Download Terraform
  curl -o terraform.zip "$terraform_url"
}

function install2system() {
  unzip -o terraform.zip

  # Provide guidance about elevated permissions
  sudo cp terraform /usr/local/bin 
}

function validate() {
  terraform -version
  if [ $? -ne 0 ]; then
    echo "Terraform validation failed. Enable set -x to debug"
  else 
    rm -f terraform terraform.zip      
  fi
}

install_prerequisite
download_terraform
install2system
validate
